version: "3.8"

services:
    k6:
        image: grafana/k6:latest
        container_name: k6
        environment:
            - K6_OUT=influxdb=http://localhost:8086
        volumes:
            - type: bind
              source: ${PWD}/k6/scripts
              target: /scripts
        network_mode: "host"  # host 네트워크 모드 사용(에러방지)
        extra_hosts:
            - "host.docker.internal:host-gateway"